### PR TITLE
Port CSS to SCSS, add gulp func, add NasaHackUVic logo to index

### PR DESCRIPTION
**Pull request by k-erby**
Closed previous PR to fix some things.

Here are all the changes:
1. Port over CSS to SCSS files.
2. Add gulp functionality to auto-convert SCSS files to CSS, as well as browsersync so you can see your local changes appear automagically. ~~(use command `gulp watch` in folder)~~ (use command `npm run build` instead)
3. Add logo SVG directly into the HTML because svgs sUCK THEY ARE SO ANNOYING OMG YOU Z-INDEX.
4. New file: animation.scss has all the img-nasa logo functionality in it (composition + animation).
5. New file: branding.scss for color and font reusability.
6. Change the darker gradient color to a soft-black. Lowered opacity on the stars.

**Things To Do:**
- Later PR: convert all css files into one lump or something.

Here's a video walkthrough of what the PR makes the site look like:
https://drive.google.com/file/d/1ZFXuV7_3WcD9G4LBOd2-By1qCJZnWE-i/view?usp=sharing

### CODE REVIEW

**Comment by FlyteWizard** [comment]
Getting Gulp Ready

1. Install gulp: `npm install gulp -g`
2. In folder, init (spam enter): `npm init`
3. In folder, add gulp: `npm install gulp --save-dev`
4. In folder, add gulp-sass: `npm install gulp-sass --save-dev`
5. In folder, add browserSync: `npm install browser-sync --save-dev`

It did create a `package.json`. 

I would prefer to have the `package.json` file in the repository, so we do not have to initialize each time. Instead we would run `npm install` to install all the necessary packages in the `package.json`. 
(We would need to add `package-lock.json` to `.gitignore`)

After following the commands above I was able to do `gulp watch`

**Comment by k-erby** [comment]
@FlyteWizard   Awesome! I'll add the gulp process to the readme and the `package.json` to the repo which I goofed out originally. 👍 

My node was old and crusty (just updated it - which is why there was no `package-lock.json` file originally) so thank you for going over the steps! The `npm install/package.json` comment is on point! From my understanding the intent behind `package-lock.json` is for it to be committed to serve as a snapshot of the dependency tree. This isn't, like, a giant app so I can see not including it as all the dependencies we actually need are in the `package.json` file. Is that your reasoning for leaving it out, too?

**Comment by FlyteWizard** [comment]
@k-erby I did some research and it is common practice (and advised) to put the `package-lock.json`, I just avoid it because of all the merge conflicts. 

I'm fine with having it in the repository.

**Comment by k-erby** [comment]
@FlyteWizard Hm, okay - cool! We can add it in and then if you find there are conflicts we can just take it out? I don't care either way. :)

**Review by FlyteWizard — APPROVED** [review]

**Pull request merged**
