### PR TITLE
Update whoopsie on git stuff in the readme

### PR DESCRIPTION
**Pull request by k-erby**

### CODE REVIEW

**Review by FlyteWizard — APPROVED** [review]
Yay Safety! 

And yes to readme stuff :D

**Comment by FlyteWizard** [comment]
🎿

**Review by k-erby — COMMENTED** [review]
🎋 wow kaitlin good job A++

**Comment by k-erby** [comment]
@FlyteWizard That emoji reminds me of the 'stupid sexy flanders' bit in the simpsons. Appreciate. 🙏 🙏 🤰

**Review by amyhanv — APPROVED** [review]
~~cool i guess~~ absolutely amazing, wow, so impressed.

**Pull request closed without merging**
